baseURL = "https://thered3rdeye.github.io/"
languageCode = "en-us"
title = "The Red 3rd Eye"
theme = "ezhil"

copyright = "© The Red 3rd Eye"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 10
summaryLength = 20

[params]
    subtitle = ""
    mainSections = ["posts"]
    featherIconsCDN = true
    favicon = "icons/myicon.png"    
    mode = "dark"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/TheRed3rdEye/thered3rdeye.github.io"

[taxonomies]
    tag = "tags"